type Query {
  products(paginationInput: PaginationInput): ProductList
  product(id: Int!): Product
}
type Mutation {
  createProduct(input: ProductInput): Boolean
  updateProduct(id: Int!, input: ProductInput): Boolean
  removeProduct(id: Int!): Boolean
}
type ProductList {
  data: [Product]
  pagination: Pagination
}
type Product {
  id: Int
  product_name: String
  image: String
  description: String
  summary: String
  price: Float
  status: String
  category: Category
}
input ProductInput {
  product_name: String
  image: String
  description: String
  summary: String
  price: Float
  status: String
  category_id: Int
}
input PaginationInput {
  page: Int
  size: Int
}

type Pagination {
  total: Int
  size: Int
  current: Int
}
